### ISSUE TITLE
non-convex operation

### ISSUE THREAD

**Issue by necozay** [kwesiRutledge/Eq-Perf-Tests#1]
Is it possible to eliminate the following operation that does no preserve convexity:

https://github.com/kwesiRutledge/Eq-Perf-Tests/blob/7914e44d908d53e86e2d511afb77e7f133f56611/functions/%40BeliefGraph/post_accel.m#L205

**Comment by necozay** [comment]
By replacing the lines 205-211 with the following (semantically equivalent) convex operation achieves about 50% speed up for the overall code:

```
if Consist_sets{ch_idx}.contains(Consist_sets{ut_idx})
	if debug_flag >= 2
		disp(['temp_diff.isEmptySet = for:'])
		disp(['- Phi1(' num2str([subL_p_set(ut_idx).words{:}]) ')' ])
		disp(['- Phi2(' num2str([subL_p_set(ch_idx).words{:}]) ')' ])
		disp(' ')
	end
	visible_transitions(ut_idx) = 0;
	empty_log(ut_idx,ch_idx) = 1;
	break;
        % elseif (ch_idx == ind_ut) && (~Projx_Phi1.isEmptySet)
	% 	visible_transitions(ind_ut) = ch_idx;
end 
```
I can send a pull request if you agree. In addition, when I change the solver to mosek, for T=5, belief graph generation time is 502s on my laptop.

**Comment by kwesiRutledge** [comment]
I agree!

Time is 502 seconds on which example?

It may be that my paltry 2 cores are not fast enough to solve things quickly. Also, there is a 'cachesolvers' option which I understand speeds up YALMIP (and I'm assuming MPT3 as a whole?), which might be worth trying.

**Comment by necozay** [comment]
``BG_timing`` for

```
results = observer_tests([60], ...
			{[' ''c_sq'', 2,1 ,' ...
				' ''L'' ,Language([1,2,2,1,1],[1,2,1,1,1],[1,1,2,1,1]),' ...
				' ''disturb_bounds'',0.35,0.2,' ...
				' ''eta_u'', 50 ']})
```
